
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    
public partial class GetServicios
{

    public string Descripcion { get; set; }

    public int Id { get; set; }

    public decimal Costo { get; set; }

    public bool Estado { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

}

}
