//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.ComponentModel.DataAnnotations;
     using Resources;
    public partial class GetUsuariosServicios
    {
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelGetUsuariosServiciosId")]
    public int Id { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelGetUsuariosServiciosDescripcionServicio")]
    public string DescripcionServicio { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelGetUsuariosServiciosNombreUsuario")]
    public string NombreUsuario { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelGetUsuariosServiciosEstado")]
    public bool Estado { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelGetUsuariosServiciosFechaCreacion")]
    public System.DateTime FechaCreacion { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelGetUsuariosServiciosFechaModificacion")]
    public Nullable<System.DateTime> FechaModificacion { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelGetUsuariosServiciosFechaInicioServicio")]
    public System.DateTime FechaInicioServicio { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelGetUsuariosServiciosFechaFinServicio")]
    public System.DateTime FechaFinServicio { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelGetUsuariosServiciosNumeroCreditos")]
    public short NumeroCreditos { get; set; }
    }
}
