//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
     using Resources;
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.UsuariosServicios = new HashSet<UsuariosServicios>();
        }
    
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelUsuariosId")]
    public int Id { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelUsuariosNombre")]
    public string Nombre { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelUsuariosUsuario")]
    public string Usuario { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelUsuariosContrasena")]
    public string Contrasena { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelUsuariosEstado")]
    public bool Estado { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelUsuariosFechaCreacion")]
    public System.DateTime FechaCreacion { get; set; }
        [Display(ResourceType = typeof(AdminRokuResourcesGlobal), Name = "LabelUsuariosFechaModificacion")]
    public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<UsuariosServicios> UsuariosServicios { get; set; }
    }
}
