
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class UsuariosServicios
{

    public int IdServicio { get; set; }

    public int IdUsario { get; set; }

    public int Id { get; set; }

    public bool Estado { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public System.DateTime FechaInicioServicio { get; set; }

    public System.DateTime FechaFinServicio { get; set; }

    public short NumeroCreditos { get; set; }



    public virtual Servicios Servicios { get; set; }

    public virtual Usuarios Usuarios { get; set; }

}

}
