//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosServicios
    {
        public int IdServicio { get; set; }
        public int IdUsario { get; set; }
        public int Id { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public System.DateTime FechaInicioServicio { get; set; }
        public System.DateTime FechaFinServicio { get; set; }
        public short NumeroCreditos { get; set; }
    
        public virtual Servicios Servicios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
